### ISSUE TITLE
Compile for Ubuntu BBB

### ISSUE THREAD

**Issue by phase1** [piranha32/IOoo#2]
Hi,

Is there a way to make this library on the BBB running Ubuntu 13.10?
Looking through the makefile, its hard coded for the angstrom distribution.

Thanks

**Comment by jadedanemone** [comment]
I've implemented autotools in my fork here: https://github.com/jadedanemone/IOoo
The README has also been updated with the appropriate build instructions. Let me know if you have any trouble.

**Comment by phase1** [comment]
Hi James,

When i run make, the terminal goes into an infinite loop.

The commands i took:
git clone https://github.com/jadedanemone/IOoo.git
autoreconf
./configure
make

This is the log of the repeating execution:
make: Warning: File `Makefile.am' has modification time 4.4e+08 s in the
future
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing aclocal-1.13
 cd . && /bin/bash /home/ubuntu/IOoo-master/missing automake-1.13 --foreign
dts/Makefile.am:4: warning: patsubst %.dts,%.dtbo,$(DTS: non-POSIX variable
name
dts/Makefile.am:4: (probably a GNU make extension)
dts/Makefile.am:6: warning: '%'-style pattern rules are a GNU make extension
dts/Makefile.am:11: warning: user target 'clean' defined here ...
automake-1.13: ... overrides Automake target 'clean' defined here
dts/Makefile.am:11: consider using clean-local instead of clean
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create
--no-recursion
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for gawk... no
checking for mawk... mawk
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking for unistd.h... (cached) yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for memset... yes
checking for munmap... yes
checking for strerror... yes
checking whether build environment is sane... yes
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating dts/Makefile
config.status: creating include/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make: Warning: File`Makefile.am' has modification time 4.4e+08 s in the
future
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing aclocal-1.13
 cd . && /bin/bash /home/ubuntu/IOoo-master/missing automake-1.13 --foreign
dts/Makefile.am:4: warning: patsubst %.dts,%.dtbo,$(DTS: non-POSIX variable
name
dts/Makefile.am:4: (probably a GNU make extension)
dts/Makefile.am:6: warning: '%'-style pattern rules are a GNU make extension
dts/Makefile.am:11: warning: user target 'clean' defined here ...
automake-1.13: ... overrides Automake target 'clean' defined here
dts/Makefile.am:11: consider using clean-local instead of clean
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create
--no-recursion
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for gawk... no
checking for mawk... mawk
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking for unistd.h... (cached) yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for memset... yes
checking for munmap... yes
checking for strerror... yes
checking whether build environment is sane... yes
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating dts/Makefile
config.status: creating include/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make: Warning: File `Makefile.am' has modification time 4.4e+08 s in the
future
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing aclocal-1.13
 cd . && /bin/bash /home/ubuntu/IOoo-master/missing automake-1.13 --foreign
dts/Makefile.am:4: warning: patsubst %.dts,%.dtbo,$(DTS: non-POSIX variable
name
dts/Makefile.am:4: (probably a GNU make extension)
dts/Makefile.am:6: warning: '%'-style pattern rules are a GNU make extension
dts/Makefile.am:11: warning: user target 'clean' defined here ...
automake-1.13: ... overrides Automake target 'clean' defined here
dts/Makefile.am:11: consider using clean-local instead of clean
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash
/home/ubuntu/IOoo-master/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create
--no-recursion
^Z
[1]+  Stopped                 make

and then it goes on to check for c++ libraries.

-Richard Chao

**Comment by piranha32** [comment]
James,

Could you please send pull request, so I can add your modifications to master?

**Comment by jadedanemone** [comment]
Jacek,

Certainly.

phase1,
I'm not able to replicate on a BBB with Ubuntu 13.04. Perhaps there's a version difference with the autotools. What versions of automake and autoconf do you have?

**Comment by phase1** [comment]
Hi James,

I'm running ubnutu 13.10 with Hard Floats,
automake - 1.13.3
autoconf - 2.69
gcc - 4.8.1

-Richard Chao

**Comment by jadedanemone** [comment]
The only thing I see in that loop that could be causing a problem is this:
make: Warning: File 'Makefile.am' has modification time 4.4e+08 s in the
future

Try setting the clock to the correct time and/or `touch Makefile.am`.

**Comment by phase1** [comment]
i did touch Makefile.am,

and it seemed to make it, heres the log:

``` make~~~~~~~~~~~~~


root@ubuntu-armhf:~/IOoo# make
 cd . && /bin/bash /root/IOoo/missing automake-1.13 --foreign Makefile
 cd . && /bin/bash ./config.status Makefile 
config.status: creating Makefile
make  all-recursive
make[1]: Entering directory `/root/IOoo'
Making all in src
make[2]: Entering directory `/root/IOoo/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT SPI
.o -MD -MP -MF .deps/SPI.Tpo -c -o SPI.o SPI.cpp
mv -f .deps/SPI.Tpo .deps/SPI.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT GPI
Ooo.o -MD -MP -MF .deps/GPIOoo.Tpo -c -o GPIOoo.o GPIOoo.cpp
mv -f .deps/GPIOoo.Tpo .deps/GPIOoo.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT Bea
gleGoo.o -MD -MP -MF .deps/BeagleGoo.Tpo -c -o BeagleGoo.o BeagleGoo.cpp
In file included from BeagleGoo.cpp:16:0:
BeagleGoo.cpp: In constructor 'BeagleGoo::BeagleGoo()':
../include/debug.h:22:116: warning: format '%x' expects argument of type 'unsigned int', but argument 6 has type 'ui
nt32_t* {aka unsigned int*}' [-Wformat=]
 #define debug(level,format,...) {if(level<=DEBUG_LEVEL){printf( "%s:%i:"#format"\n",__FILE__,__LINE__,##__VA_ARGS__
);}}

^
BeagleGoo.cpp:127:3: note: in expansion of macro 'debug'
   debug(1,
   ^
mv -f .deps/BeagleGoo.Tpo .deps/BeagleGoo.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT Bea
gleGooP.o -MD -MP -MF .deps/BeagleGooP.Tpo -c -o BeagleGooP.o BeagleGooP.cpp
mv -f .deps/BeagleGooP.Tpo .deps/BeagleGooP.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT HD4
4780.o -MD -MP -MF .deps/HD44780.Tpo -c -o HD44780.o HD44780.cpp
mv -f .deps/HD44780.Tpo .deps/HD44780.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT HD4
4780gpioPhy.o -MD -MP -MF .deps/HD44780gpioPhy.Tpo -c -o HD44780gpioPhy.o HD44780gpioPhy.cpp
mv -f .deps/HD44780gpioPhy.Tpo .deps/HD44780gpioPhy.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT TLC
5946phy.o -MD -MP -MF .deps/TLC5946phy.Tpo -c -o TLC5946phy.o TLC5946phy.cpp
mv -f .deps/TLC5946phy.Tpo .deps/TLC5946phy.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT TLC
5946chain.o -MD -MP -MF .deps/TLC5946chain.Tpo -c -o TLC5946chain.o TLC5946chain.cpp
mv -f .deps/TLC5946chain.Tpo .deps/TLC5946chain.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT TLC
5946PRUSSphy.o -MD -MP -MF .deps/TLC5946PRUSSphy.Tpo -c -o TLC5946PRUSSphy.o TLC5946PRUSSphy.cpp
mv -f .deps/TLC5946PRUSSphy.Tpo .deps/TLC5946PRUSSphy.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT JDT
18003T01.o -MD -MP -MF .deps/JDT18003T01.Tpo -c -o JDT18003T01.o JDT18003T01.cpp
mv -f .deps/JDT18003T01.Tpo .deps/JDT18003T01.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT ST7
735.o -MD -MP -MF .deps/ST7735.Tpo -c -o ST7735.o ST7735.cpp
mv -f .deps/ST7735.Tpo .deps/ST7735.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT ST7
735phy.o -MD -MP -MF .deps/ST7735phy.Tpo -c -o ST7735phy.o ST7735phy.cpp
mv -f .deps/ST7735phy.Tpo .deps/ST7735phy.Po
rm -f libgpiooo.a
ar cru libgpiooo.a SPI.o GPIOoo.o BeagleGoo.o BeagleGooP.o HD44780.o HD44780gpioPhy.o TLC5946phy.o TLC5946chain.o TL
C5946PRUSSphy.o JDT18003T01.o ST7735.o ST7735phy.o 
ranlib libgpiooo.a
make[2]: Leaving directory `/root/IOoo/src'
Making all in examples
make[2]: Entering directory `/root/IOoo/examples'
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT TestLCD.o -MD -MP 
-MF .deps/TestLCD.Tpo -c -o TestLCD.o TestLCD.cpp
mv -f .deps/TestLCD.Tpo .deps/TestLCD.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT gpio_lcd.o -MD -MP
 -MF .deps/gpio_lcd.Tpo -c -o gpio_lcd.o gpio_lcd.cpp
mv -f .deps/gpio_lcd.Tpo .deps/gpio_lcd.Po
g++  -g -O2 -std=gnu++11 -L../lib -L../src  -o gpio_lcd TestLCD.o gpio_lcd.o ../src/libgpiooo.a 
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT gpio_buttons.o -MD
 -MP -MF .deps/gpio_buttons.Tpo -c -o gpio_buttons.o gpio_buttons.cpp
mv -f .deps/gpio_buttons.Tpo .deps/gpio_buttons.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT TestGPIOButtons.o 
-MD -MP -MF .deps/TestGPIOButtons.Tpo -c -o TestGPIOButtons.o TestGPIOButtons.cpp
mv -f .deps/TestGPIOButtons.Tpo .deps/TestGPIOButtons.Po
g++  -g -O2 -std=gnu++11 -L../lib -L../src  -o gpio_buttons gpio_buttons.o TestGPIOButtons.o ../src/libgpiooo.a 
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT gpio_leds.o -MD -M
P -MF .deps/gpio_leds.Tpo -c -o gpio_leds.o gpio_leds.cpp
mv -f .deps/gpio_leds.Tpo .deps/gpio_leds.Po
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT TestGPIOLeds.o -MD
 -MP -MF .deps/TestGPIOLeds.Tpo -c -o TestGPIOLeds.o TestGPIOLeds.cpp
mv -f .deps/TestGPIOLeds.Tpo .deps/TestGPIOLeds.Po
g++  -g -O2 -std=gnu++11 -L../lib -L../src  -o gpio_leds gpio_leds.o TestGPIOLeds.o ../src/libgpiooo.a 
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE    -g -O2 -std=gnu++11 -MT test_jd-t18003-t01
.o -MD -MP -MF .deps/test_jd-t18003-t01.Tpo -c -o test_jd-t18003-t01.o test_jd-t18003-t01.cpp
test_jd-t18003-t01.cpp: In function 'int main()':
test_jd-t18003-t01.cpp:27:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   { "P8_19", "P8_18" };
                      ^
test_jd-t18003-t01.cpp:27:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
test_jd-t18003-t01.cpp:29:19: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   { "rs", "reset" };
                   ^
test_jd-t18003-t01.cpp:29:19: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
mv -f .deps/test_jd-t18003-t01.Tpo .deps/test_jd-t18003-t01.Po
g++  -g -O2 -std=gnu++11 -L../lib -L../src  -o test_jd-t18003-t01 test_jd-t18003-t01.o ../src/libgpiooo.a 
make[2]: Leaving directory `/root/IOoo/examples'
Making all in dts
make[2]: Entering directory `/root/IOoo/dts'
dtc -O dtb -o gpio_hd44780-00A0.dtbo -b 0 -@ gpio_hd44780-00A0.dts
dtc -O dtb -o gpio_leds-00A0.dtbo -b 0 -@ gpio_leds-00A0.dts
dtc -O dtb -o tlc5946-00A0.dtbo -b 0 -@ tlc5946-00A0.dts
dtc -O dtb -o gpio_buttons-00A0.dtbo -b 0 -@ gpio_buttons-00A0.dts
dtc -O dtb -o spi1-00A0.dtbo -b 0 -@ spi1-00A0.dts
dtc -O dtb -o jd-t18003-ctrl-00A0.dtbo -b 0 -@ jd-t18003-ctrl-00A0.dts
make[2]: Leaving directory `/root/IOoo/dts'
Making all in include
make[2]: Entering directory `/root/IOoo/include'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/IOoo/include'
make[2]: Entering directory `/root/IOoo'
make[2]: Leaving directory `/root/IOoo'
make[1]: Leaving directory `/root/IOoo'


~~~~~~~make install here~~~~~~~~~~~~~~



root@ubuntu-armhf:~/IOoo# sudo make install
Making install in src
make[1]: Entering directory `/root/IOoo/src'
make[2]: Entering directory `/root/IOoo/src'
 /bin/mkdir -p '/usr/local/lib'
 /usr/bin/install -c -m 644  libgpiooo.a '/usr/local/lib'
 ( cd '/usr/local/lib' && ranlib libgpiooo.a )
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/IOoo/src'
make[1]: Leaving directory `/root/IOoo/src'
Making install in examples
make[1]: Entering directory `/root/IOoo/examples'
make[2]: Entering directory `/root/IOoo/examples'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/IOoo/examples'
make[1]: Leaving directory `/root/IOoo/examples'
Making install in dts
make[1]: Entering directory `/root/IOoo/dts'
make[2]: Entering directory `/root/IOoo/dts'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/IOoo/dts'
make[1]: Leaving directory `/root/IOoo/dts'
Making install in include
make[1]: Entering directory `/root/IOoo/include'
make[2]: Entering directory `/root/IOoo/include'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /bin/mkdir -p '/usr/local/include/device'
 /usr/bin/install -c -m 644  device/HD44780.h device/HD44780gpioPhy.h device/HD44780phy.h device/JDT18003T01.h devic
e/ST7735.h device/ST7735phy.h device/TLC5946PRUSSphy.h device/TLC5946chain.h device/TLC5946phy.h '/usr/local/include
/device'
 /bin/mkdir -p '/usr/local/include/beaglebone'
 /usr/bin/install -c -m 644  beaglebone/BeagleGoo.h beaglebone/BeagleGooP.h '/usr/local/include/beaglebone'
 /bin/mkdir -p '/usr/local/include/pruss'
 /usr/bin/install -c -m 644  pruss/pruss_intc_mapping.h pruss/prussdrv.h '/usr/local/include/pruss'
make[2]: Leaving directory `/root/IOoo/include'
make[1]: Leaving directory `/root/IOoo/include'
make[1]: Entering directory `/root/IOoo'
make[2]: Entering directory `/root/IOoo'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/IOoo'
make[1]: Leaving directory `/root/IOoo'



could you let me know if everything compiled properly?
```

**Comment by jadedanemone** [comment]
Looks like it. I don't see any errors, and the library is definitely installed.

**Comment by phase1** [comment]
Thanks so much for your help guys!
