### ISSUE TITLE
Question: How to include library in C++ project 

### ISSUE THREAD

**Issue by bigbrett** [piranha32/IOoo#20]
Hi,

I was wondering how I might be able to include the library for code I have written. I am unable to find anything in /usr/src or any of the other standard install directories on the beaglebone. 

Are there .a files or .so files that running make install generates? Or must we build the libraries ourselves. 

Could you please provide an example of what files I would need to include, and an example invocation to g++ that I would need to use if I wanted to write a program that utilized the beaglebone's SPI interface via your library? 

Thanks!

Brett

**Comment by piranha32** [comment]
The library is not available as a package in default Debian distro for Beaglebone. You can install it by following instructions from README: https://github.com/piranha32/IOoo#building-and-installation-instructions

**Comment by piranha32** [comment]
For examples of use please refer to the files in `examples` directory. IOoo is compiled to static library which will be linked with your application at the time of linking, so you won't need to distribute any additional resources, except what is required by your application.
