### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by CJxD** [piranha32/IOoo#6]
May be related to issue #4.

Line 136 in BeagleGooP.cpp calls the following code:

```
debug(2,
        "BeagleGooP::enableOutput(): enabling pin %i (%s): port=%i, mask=%08x, OE_REG=%08x\n",
        i, localNames[i], ports[i], masks[i],
        parent->gpios[ports[i]][GPIO_OE_REG / 4]);
```

On my BeagleBone running their own release of Debian 7 with Linux 3.13, this causes a bus error. In particular the following statement `parent->gpios[ports[i]][GPIO_OE_REG / 4]`.

The `gpios[ports[i]]` bit is fine, it's just trying to access the OE_REG offset that's the issue here. I'll see what happens if I export the GPIOs as suggested in the other issue whatever that means.

**Comment by CJxD** [comment]
Yeah running tools/bbb_enable_gpio.sh did the trick.

**Comment by piranha32** [comment]
Did you export GPIO? The GPIO module must be enabled, otherwise you'll get BUS error. Please see my comment to #4 and post referenced in bbb_enable_gpio.sh

**Comment by piranha32** [comment]
I'm glad to see you got it working. Exporting the pins is a very hackish way to enable the modules, but simple and effective.
